apiVersion: v1
kind: ConfigMap

metadata:
  name: secure-cicd-demo-config
  namespace: {{ .Release.Namespace }}

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_ENV: {{ .Values.config.appEnv | quote }}