apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "secure-cicd-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secure-cicd-demo.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "secure-cicd-demo.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "secure-cicd-demo.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: secure-cicd-demo

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: secure-cicd-demo-config

            - secretRef:
                name: secure-cicd-demo-secret

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: 5000
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: 5000
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}