apiVersion: v1
kind: Service

metadata:
  name: secure-cicd-demo
  namespace: secure-cicd-demo

spec:
  type: NodePort

  selector:
    app: secure-cicd-demo

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500